services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_containerbda
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: actividad_db
    ports:
      - "127.0.0.1:5436:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d actividad_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: