services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_containerbda
    restart: unless-stopped
    environment:
      POSTGRES_USER: userpp
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: actividad_db
    ports:
      - "5436:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userpp -d actividad_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://userpp:pass123@postgres:5432/actividad_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: